/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 */

#ifndef __QPACE_INTERNAL_H__
#define __QPACE_INTERNAL_H__

#include <linux/bits.h>
#include <linux/bitfield.h>

/* hardware definitions and opcode values */
#define NUM_TRS_ERS_URG_CMD_REGS 8
#define QPACE_HW_VERSION_V2 0x2000000
#define DEFAULT_SMMU_CONTEXT 0

#define LZ4_COMP 0x9
#define LZ4_DECOMP 0xa

#define OP_OK 0x0
#define OP_BUS_ERROR 0x1
#define OP_COMP_TOO_BIG 0x2
#define OP_TIMED_OUT 0x5
#define OP_URG_ONGOING 0xf

#define LLC_ALLOC 0x1

#define URG_CMD_CONTEXT_SPACING 0x10

#define QPACE_RUN 0x1
#define QPACE_STOP 0x0
#define QPACE_STATE_CHANGE_TIMEOUT_US 10000

/* register offsets */
#define QPACE_GEN_CORE_REGS_OFFSET 0x1000
#define QPACE_COMP_CORE_REGS_OFFSET 0x2000
#define QPACE_DECOMP_CORE_REGS_OFFSET 0x6000
#define QPACE_URG_REGS_OFFSET 0x10000

#define QPACE_CORE_HW_VERSION_OFFSET 0x0
#define QPACE_CORE_QNS4_CFG_OFFSET 0x14
#define CORE_QNS4_CFG_CACHEINDEX GENMASK(17, 12)

#define QPACE_CORE_GEN_CFG_OFFSET 0x18
#define CORE_GEN_CFG_QMB2_MAX_RD_OUTST_LIMIT GENMASK(13, 7)
#define CORE_GEN_CFG_QMB2_MAX_WR_OUTST_LIMIT GENMASK(6, 0)

#define QPACE_CORE_URG_CMD_n_CACHEINDEX_CFG_OFFSET 0x2fc
#define CORE_URG_CMD_n_CACHEINDEX__ENGINE_CACHEINDEX_OVERRIDE BIT(6)
#define CORE_URG_CMD_n_CACHEINDEX__ENGINE_CACHEINDEX GENMASK(5, 0)

#define QPACE_CORE_OPER_CORE_RUN_STOP_OFFSET 0x0
#define QPACE_CORE_OPER_CORE_READY_OFFSET 0x4
#define QPACE_CORE_OPER_CFG_OFFSET 0x8
#define CORE_OPER_CFG_COMP_MEM_PWR_DWN_1 BIT(3)

#define QPACE_COMP_CORE_CFG_OFFSET 0x0
#define COMP_CORE_CFG_DMA_WR_MAX_OT GENMASK(17, 13)
#define COMP_CORE_CFG_DMA_RD_MAX_OT GENMASK(12, 8)
#define QPACE_COMP_CORE_BULK_MODE_OFFSET 0x4
#define COMP_CORE_BULK_MODE_ALL_CORES GENMASK(5, 0)

#define QPACE_DECOMP_CORE_CFG_OFFSET 0x0
#define DECOMP_CORE_CFG_DECOMP_DMA_MEM_MNG_PAGE_SIZE GENMASK(12, 10)
#define DECOMP_CORE_CFG_DMA_WR_MAX_OT GENMASK(9, 5)
#define DECOMP_CORE_CFG_DMA_RD_MAX_OT GENMASK(4, 0)

#define QPACE_URG_CMD_0_TD_DST_ADDR_L_CFG_CNTXT_OFFSET 0x0
#define URG_CMD_0_TD_DST_ADDR_L__CMD_CFG_CNTXT GENMASK(3, 0)
#define QPACE_URG_CMD_0_ED_STAT_OFFSET 0x18
#define URG_CMD_0_ED_STAT_COMP_CODE GENMASK(23, 20)
#define URG_CMD_0_ED_STAT_SIZE GENMASK(19, 0)
#define QPACE_URG_CMD_0_STAT_CLR_OFFSET 0x28
#define URG_CMD_0_STAT_CLR_REQ_ON_ACTIVE_ERR BIT(1)
#define QPACE_URG_CMD_0_CFG_CNTXT_SIZE_n_OFFSET 0x40
#define URG_CMD_0_CFG_CNTXT_SIZE_SIZE GENMASK(19, 0)
#define QPACE_URG_CMD_0_CFG_CNTXT_MISC_n_OFFSET 0x48
#define URG_CMD_0_CFG_CNTXT_MISC_WA BIT(21)
#define URG_CMD_0_CFG_CNTXT_MISC_DCTX GENMASK(17, 16)
#define URG_CMD_0_CFG_CNTXT_MISC_SCTX GENMASK(15, 14)
#define URG_CMD_0_CFG_CNTXT_MISC_PAGE_CNT GENMASK(13, 8)
#define URG_CMD_0_CFG_CNTXT_MISC_OPER GENMASK(7, 4)

#endif /* __QPACE_INTERNAL_H__ */
